services:
  geth:
    image: ${REGISTRY_URL}/${STARCHAIN_NODE_IMAGE}
    container_name: "${DOCKER_NAME:-starchain-testnet-node}"
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/usr/starchain/data